name: hcore-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Runing on container
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: ./build.sh configure

    - name: Compile
      run: ./build.sh compile

    - name: Test
      run: ./build.sh test
      
    - name: Commit and push build number
      run: |
        git config --local user.email "yilupiaoxuewhq@163.com"
        git config --local user.name "GitHub Action"
        git add .build_number .gcmake/.version
        git commit -m "Update .build_number and .version [skip ci]"
        git push origin HEAD:master

    - name: Send mailer
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 【Github Action】hcore-ci result
        to: ${{ secrets.MAIL_RECIPIENT }}, ${{ secrets.MAIL_RECIPIENT }}
        from: ${{ secrets.MAIL_USERNAME }}
        body: Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} completed with status ${{ job.status }}. See details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

