name: hcore-release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build image
      uses: actions/checkout@v3
      with:
        context: .
        dockerfile: Dockerfile

    - name: Configure CMake
      run: ./build.sh -n configure

    - name: Compile
      run: ./build.sh -n compile

    - name: Test
      run: ./build.sh -n test

